os:
  - linux
language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libgtest-dev libstdc++ libc++-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script: ./configure && cd build && make && make test
