os:
  - linux
language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libgtest-dev libc++-dev
script: ./configure && cd build && make && make test
